### ISSUE TITLE
Add a feature to control the size and location of the window

### ISSUE THREAD

**Issue by waseeld** [alifcommunity/webui#1]
This feature can be added via the command line.
Example for chrome :
`--window-size=1024,600
--window-position=600,600`

**Comment by hassandraga** [comment]
I will modify it so the user have full control of this feature, like change values, or even disable it. Thank you.

**Comment by hassandraga** [comment]
I see your point now, thank you, we will implement this soon.

**Comment by hassandraga** [comment]
We need to search what is the best way, is using CLI or Javascript.

**Comment by hassandraga** [comment]
No need for this feature as the browser doing it naturally. Thanks.
