### ISSUE TITLE
Project not working

### ISSUE THREAD

**Issue by InactivatedPyschiopath** [alifcommunity/webui#13]
it builds and runs with no error but it doesn't work and shows nothing.

Windows 10 - VS 2019

**Comment by hassandraga** [comment]
Hi, did you follow the instructions? and which example did you run?

**Comment by RossetaGotStoned** [comment]
It doesn't throw any error it just not work and exe reach the end of it, default project.

**Comment by Shad7ows** [comment]
> It doesn't throw any error it just not work and exe reach the end of it, default project.

Salam Rosseta,
You don't need to build it to use it, only download it from this link : https://www.aliflang.org/download/Alif_Compiler_v3.0.1_Win64.zip

Then place it in C:\\ driver or your System driver

Then add it to Environment Variables

Last open CMD as adminstration and just write Alif3 to insure it's working correctly

**Comment by hassandraga** [comment]
@RossetaGotStoned Did the web browser run (_Maybe blank window_)? Can you please provide the cmake command you used to generate VS project files?, I will appreciated, Thank you.

**Comment by hassandraga** [comment]
You build the library as shared or static?

**Comment by RossetaGotStoned** [comment]
I used static version and I use cmake gui
I can upload it if you want

**Comment by hassandraga** [comment]
Yes please, this will help us to quickly identify the problem and fixed.

**Comment by hassandraga** [comment]
I just test it, VS 2019, Boost 1.76 (lib64-msvc-14.2), and it's working fine, probably WebUI failed to find any browser. Can you please try run this command `start chrome` or `start firefox`
