### ISSUE TITLE
error: ‘paddressort’ was not declared in this scope; did you mean ‘address’?

### ISSUE THREAD

**Issue by MuhammadSawalhy** [alifcommunity/webui#15]
<div dir=rtl>

هذا الخطأ يحدث أثناء البناء بالأمر:

</div>

```
cmake .. && make && sudo make install
```

<div dir=rtl>

وهذا هو ما يظهر

</div>

![image](https://user-images.githubusercontent.com/42011920/124607800-b4b4ba80-de5d-11eb-944e-7c9142ccb580.png)

**Comment by hassandraga** [comment]
آسف خطأ مني
فقط غيره إلى
address

**Comment by hassandraga** [comment]
Fixed.
