### ISSUE TITLE
No window on Linux

### ISSUE THREAD

**Issue by hassandraga** [alifcommunity/webui#16]
![123605629-927ec500-d7eb-11eb-96d2-d2f2d73b509c](https://user-images.githubusercontent.com/16948659/124608168-7f4ba500-de3c-11eb-965b-f10cdf512ec4.png)

Original: https://github.com/alifcommunity/compiler/issues/29

**Comment by hassandraga** [comment]
WebUI check if Firefox is installed on your system using this command: 
`firefox -v >>/dev/null 2>>/dev/null`

If yes, Then WebUI create a new Firefox profile: 
`sh -c " firefox -CreateProfile "WebUI /var/tmp/WebUIFirefoxProfile" >>/dev/null 2>>/dev/null"`

If yes, Then WebUI run Firefox: 
`sh -c " firefox -P WebUI -private -no-remote -new-instance http://google.com >>/dev/null 2>>/dev/null"`

Can you please run those commands manually and see if it's work?
Can you please also provide your OS info?

**Comment by hassandraga** [comment]
which OS you have?

**Comment by MuhammadSawalhy** [comment]
```
OS: Arch Linux x86_64
Kernel: 5.12.12-arch1-1 
> firefox -v
Mozilla Firefox 89.0.1
```

**Comment by hassandraga** [comment]
@MuhammadSawalhy 
Thank you, All the three commands run well?

**Comment by MuhammadSawalhy** [comment]
> @MuhammadSawalhy
> Thank you, All the three commands run well?

*YES*

**Comment by waseeld** [comment]
guys any update about this ?

**Comment by MuhammadSawalhy** [comment]
> If yes, Then WebUI create a new Firefox profile: `sh -c " firefox -CreateProfile "WebUI /var/tmp/WebUIFirefoxProfile" >>/dev/null 2>>/dev/null"`

Here is the issue, as I hope. You forgot to escape quotations inside the string which represents the command. So change it to be: 

```bash
sh -c "firefox -CreateProfile WebUI" &> /dev/null
```

**Comment by hassandraga** [comment]
Fixed. Thank you.
