### ISSUE TITLE
 Add new button

### ISSUE THREAD

**Issue by dinglizhi** [alifcommunity/webui#18]
JS after using document. Getelementbyid ("indextext"). InnerHTML = a new button is added, but the bound event is invalid.

**Comment by hassandraga** [comment]
True, good catch, we will need to implement an easy way to update events listener. for now you can do it manually by calling this JS function `_webui_listener()`

**Comment by dinglizhi** [comment]
> 是的，很好，我们需要实现一种简单的方法来更新事件监听器。现在你可以通过调用这个 JS 函数来手动完成`_webui_listener()`

Ok,thank you.
