### ISSUE TITLE
Is it possible to access the UI from another PC?

### ISSUE THREAD

**Issue by me21** [alifcommunity/webui#20]
Hello,

Is the UI exposed to LAN or is it local PC only?

**Comment by hassandraga** [comment]
It's listening to local IP (127.0.0.1), [see this line](https://github.com/alifcommunity/webui/blob/21991ee35ab0575dc70b9d1a99692dc7df8fbf2b/src/webui.cpp#L2481), like any normal web server, so it's safe, but you can allow a specific port in your firewall for example 8080, then force [getport()](https://github.com/alifcommunity/webui/blob/21991ee35ab0575dc70b9d1a99692dc7df8fbf2b/src/webui.cpp#L2099) to return 8080 as a workaround.

In the next version a new option will be added to select a specific port number.
