### ISSUE TITLE
possible to use webui with golang

### ISSUE THREAD

**Issue by passerbyo** [alifcommunity/webui#21]

**Comment by hassandraga** [comment]
Yes you can, Golang can use C++ libraries, and also cWebUI has necessary exports if needed. I will probably write an example for Golang soon.

**Comment by hassandraga** [comment]
You can now build `WebUI 2.0` with your favorite C compiler, and use Golang to load the DLL. I will write an example soon.

**Comment by hassandraga** [comment]
Now the Go wrapper use the static version of WebUI.
https://github.com/alifcommunity/webui/tree/main/examples/Go/hello_world
