### ISSUE TITLE
VUE3 + TS + Naive

### ISSUE THREAD

**Issue by 204065248** [alifcommunity/webui#22]
Sorry, my English is not very good, may I ask how VUE3 + TS + Naive GUI can be loaded using this library

**Comment by hassandraga** [comment]
If you are looking to use TypeScript you can use Node.Js instead
You can easily write a sample C program that run `system("nodejs.exe example.ts")` and send back result to your GUI using WebUI
I will write an example soon..

**Comment by hassandraga** [comment]
You can see [examples here](https://github.com/alifcommunity/webui/tree/main/examples/TypeScript/Nodejs) to do that. There is two different ways based on your needs.
