### ISSUE TITLE
Why Firefox does not have the name at the top left?

### ISSUE THREAD

**Issue by AlbertShown** [alifcommunity/webui#28]
Someone asked me why Firefox does not have the name at the top left.

**Comment by hassandraga** [comment]
It's a CSS issue, WebUI creates the `userChrome.css` file to make Firefox looks like a normal desktop app as possible. You can try changing the CSS code to improve the look and shows the title at the top left.

WebUI Code:
https://github.com/alifcommunity/webui/blob/main/src/webui.c#L1426

Windows Profile Folder:
`%USERPROFILE%\.WebUI\WebUIFirefoxProfile\chrome`

Linux Profile Folder:
`/tmp/.WebUI/WebUIFirefoxProfile/chrome`

**Comment by hassandraga** [comment]
Fixed https://github.com/alifcommunity/webui/commit/b9a217e7290569751bbbe96665550930dbe7240b
