### ISSUE TITLE
How is it differ from a server?

### ISSUE THREAD

**Issue by RechieKho** [alifcommunity/webui#30]
It sounds like a server but rephrase in a different way.

**Comment by hassandraga** [comment]
As already mentioned in the [Readme](https://github.com/alifcommunity/webui/blob/main/README.md) file:
> WebUI it's not a web-server solution or a framework, but it's an easy-embeddable tool to use any installed web browser as a user interface.

WebUI won't replace any existing web server software. Instead, WebUI can help you to avoid creating a +100MB software using an embedded Chromium web browser under Electron to ~2MB portable software using the existing web browser on your customer's machines.

**Comment by RechieKho** [comment]
Understandable, have a nice day.
