### ISSUE TITLE
[Question] Can I embed `webui` in another GUI?

### ISSUE THREAD

**Issue by FilipeMarch** [alifcommunity/webui#31]
I write cross-platforms applications using the python framework [Kivy](https://github.com/kivy/kivy).
When I saw your project I wondered if we would be able to embed a webview inside the kivy window. This would be really, really useful. Our Window core provider is SDL2. 

Do you believe `webui` will be able to run inside an existing GUI, or it will always launch a new window? Do you believe it may be possible to run it inside a kivy application? 

Thanks

**Comment by hassandraga** [comment]
I don't think so. The idea behind [WebUI](https://webui.me) is to not use any legacy GUI library, only a real web browser, which makes the application portable, independent, and lightweight. Perhaps, you can try to embed this [WebView](https://github.com/webview/webview), it's good and cross-platform.
