### ISSUE TITLE
unrecognised option '-mbig-obj'

### ISSUE THREAD

**Issue by ms2052001** [alifcommunity/webui#4]
<div dir=rtl>

عند البناء بوجود هذا العلم (FLAG) لعملية ترجمة الـ webui يحدث مشكلة عند تشغيل الأمر `make` ولا يتم البناء.

<div dir=ltr>

```
~/myp/alif/webui/build main
❯ make
[ 16%] Building CXX object webui/CMakeFiles/webui.dir/webui.cpp.o
as: unrecognised option '-mbig-obj'
make[2]: *** [webui/CMakeFiles/webui.dir/build.make:63: webui/CMakeFiles/webui.dir/webui.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:155: webui/CMakeFiles/webui.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

</div>

### هذا هو سبب العطب.

![image](https://user-images.githubusercontent.com/42011920/111621351-91072f00-87f0-11eb-9d06-97f6b9c60b47.png)

</div>

**Comment by waseeld** [comment]
شكرا لك أخي على الابلاغ ...
