### ISSUE TITLE
Importing js frameworks

### ISSUE THREAD

**Issue by professor-pickles** [alifcommunity/webui#48]
Is it possible to import JavaScript frameworks or external .js files using HTML script tag? Haven't been successful this far; I just want to verify it's a code issue and not just an error on my part...

**Comment by professor-pickles** [comment]
Not sure my issue with use, but it is definitely being loaded. Closing issue...

**Comment by hassandraga** [comment]
Normally if your UI needs to load external files then is better to use the `serve a folder` example. However, glad that your issue is already solved.
