### ISSUE TITLE
Kiosk mode

### ISSUE THREAD

**Issue by AlbertShown** [alifcommunity/webui#49]
We should add in the future Kiosk mode.

**Comment by malisipi** [comment]
For chrome/chromium, `%s --chrome-frame --kiosk "%s"` can be used

**Comment by AlbertShown** [comment]
It seems reasonable to me. And the API should be `void webui_set_kiosk(bool status)`.

**Comment by malisipi** [comment]
I'm working on kiosk mode and I got the error. How can i fix it?
```
../../../src/webui.c:446:6: error: conflicting types for 'webui_set_kiosk'
void webui_set_kiosk (void* win, bool kiosk){
     ^
../../../include/webui.h:152:19: note: previous declaration is here
WEBUI_EXPORT bool webui_set_kiosk(void* window, bool kiosk);
                  ^
1 error generated.
```

**Comment by hassandraga** [comment]
> WebUI v2.3.0
> * Kiosk mode support. Thanks to @malisipi

Thank you @malisipi
