### ISSUE TITLE
it wont detect ungoogled-chromium

### ISSUE THREAD

**Issue by CardealRusso** [alifcommunity/webui#56]

**Comment by CardealRusso** [comment]
it seems like chromium dont work at all on windows

**Comment by neroist** [comment]
It seems like it doesn't, even when Chromium is added to path... In fact the string "chromium" is only found in the source code once.

**Comment by hassandraga** [comment]
I tested Chromium on Linux a while ago, but not on Windows. I will look into this today.

Thanks for reporting.
