### ISSUE TITLE
MAC os support

### ISSUE THREAD

**Issue by gregpalaci** [alifcommunity/webui#59]
Anything to try with clang or gcc, otherwise a ticket to watch support.

**Comment by hassandraga** [comment]
In [WebUI 1.x](https://github.com/alifcommunity/webui/releases/tag/1.0.20) (_Written in C++_), someone was maintaining the Mac support. Currently, WebUI 2.x is wholly rewritten in `C`, and no one has yet created a PR for Mac.

If no one creates a PR for Mac in the next week or two, then I will work on it. It's just a one-weekend day job. Please keep this open. Thank you for reporting.

**Comment by cowboyd** [comment]
@hassandraga I'd give it a shot, but it doesn't look like the build process is documented anywhere. Any tips on where to get started?

**Comment by AlbertShown** [comment]
Hi @cowboyd, The build process is very simple, take a look on the [Linux build](https://github.com/alifcommunity/webui/tree/main/build/Linux) as it should be similar to macOS.

This is the how [Firefox run in macOS](https://github.com/alifcommunity/webui/blob/9aca227129c506d31ca080ebd0234a6810792167/src/webui.c#L1819) in the code, you can search '_macOS_' keyword in the code to see the other commands that still need to be implemented. I guess no C code is needed, but we need someone that have a macOS, and he know how to run web browsers from command line.

In the other hand, you can simply test and share with us the commands result before & after installing the browsers, me or someone will implement it.

**Google Chrome**
Check if browser exist by the returning code: `open -R -a "Google Chrome"`
Browser path: `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome`

**Firefox**
Check if browser exist by the returning code: `open -R -a "firefox"`
Browser path: `/Applications/Firefox\ Firefox.app/Contents/MacOS/Firefox\ firefox`

**Epic Browser**
Check if browser exist by the returning code: `open -R -a "Epic"`
Browser path: `/Applications/Epic\ Epic.app/Contents/MacOS/Epic\ Epic`

**Vivaldi Browser**
Check if browser exist by the returning code: `open -R -a "Vivaldi"`
Browser path: `/Applications/Vivaldi\ Vivaldi.app/Contents/MacOS/Vivaldi\ Vivaldi`

**Brave Browser**
Check if browser exist by the returning code: `open -R -a "Brave"`
Browser path: `/Applications/Brave\ Brave.app/Contents/MacOS/Brave\ Brave`

**Yandex Browser**
Check if browser exist by the returning code: `open -R -a "Yandex"`
Browser path: `/Applications/Yandex\ Yandex.app/Contents/MacOS/Yandex\ yandex-browser`

**Chromium Browser**
Check if browser exist by the returning code: `open -R -a "Chromium"`
Browser path: `/Applications/Chromium\ Chromium.app/Contents/MacOS/Chromium\ chromium`

Someone last year tested and implemented the Google Chrome commands on macOS, but the other browser's command is just our imagination! never tested before.

**Comment by cowboyd** [comment]
I add a build for MacOS. For some context, I'm trying to get this running with Deno and MacOS. It does appear to work, however, the `hello_world.ts` return immediately, and does not wait for `webui.wait();`

**Comment by gregpalaci** [comment]
open -a "Google Chrome" worked but not with -R flag

**Comment by AlbertShown** [comment]
Thank you for the macOS support.

About the issue, I re-test it in Windows using Chrome, and it seems to be working. Can you please follow those steps to share the log:

1. Re-build the lib using `make debug` command
2. Copy `webui-2-x64.dyn` in `examples/TypeScript/Deno/module`
3. Run `deno run --allow-all --unstable hello_world.ts`
4. Share the logs here

**Comment by AlbertShown** [comment]
> open -a "Google Chrome" worked but not with -R flag

Indeed, `open -R -a "Google Chrome"` is the way how WebUI checks quickly if Google Chrome is installed, it's supposed not to run it.

To run it, WebUI will use something like that `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --user-data-dir="/tmp/WebUIChromeProfile" --no-first-run --disable-gpu --disable-software-rasterizer --no-proxy-server --safe-mode --disable-extensions --disable-background-mode --disable-plugins --disable-plugins-discovery --disable-translate --bwsi --disable-sync --incognito --app=http://localhost:123456`.

**Comment by AlbertShown** [comment]
@cowboyd You can re-test it using the last commit. If you still have an issue with `webui.wait();`, please feel free to open a new one.

**Comment by gregpalaci** [comment]
> 

file:///Users/carflow/Sites/newwebui/webui/examples/TypeScript/Deno/module/webui.ts:5340: Uncaught TypeError: Deno.UnsafePointer.create is not a function

But it does open in chrome, opens in chrome no matter what actually

**Comment by AlbertShown** [comment]
@gregpalaci, Are you trying to run a TypeScript example? if yes, please make sure you are using the latest Deno, as they just recently did major changes on pointers support using v8. I test it using Deno v1.31.3.

> I guess that is built into the binary via include/webui.h ?

Yes, if your UI calls `.js` or `.ts` files, WebUI tries to interpret those files using Deno or Nodejs if available. But you can fully control this behavior using APIs.

```c
webui_script_runtime(my_window, webui.runtime.deno); // Deno
webui_script_runtime(my_window, webui.runtime.nodejs); // Nodejs
webui_script_runtime(my_window, webui.runtime.none); // Disable this feature
```

**Comment by AlbertShown** [comment]
@gregpalaci I just discovered that we forgot to update the Deno examples to WebUI v2.1.1. I will update it soon. Thank you for pointing this out.

**Comment by gregpalaci** [comment]
deno 1.29.2 (release, aarch64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4
just FYI

**Comment by hassandraga** [comment]
Starting from Deno 1.31 (_Replace pointer integers with v8::External objects_), which is used by `webui.ts`. I think you should upgrade your Deno to the latest.

**Comment by gregpalaci** [comment]
> **Brave Browser**
> Check if browser exist by the returning code: `open -R -a "Brave"`
> Browser path: `/Applications/Brave\ Brave.app/Contents/MacOS/Brave\ Brave`

 `open -R -a "Brave Browser"` 

Brave doesn't work

**Comment by AlbertShown** [comment]
`open -R -a "Brave Browser"` won't run the browser, but it returns the exit code, `0` mean it exists, otherwise, it means it does not exist.

The latest commit support Chrome in macOS. The support for Brave in macOS is also included but has yet to be tested. Can you please try `open -W "/Applications/Brave.app"`? Or, simply clone the latest commit and run the examples.

**Comment by gregpalaci** [comment]
open -W "/Applications/Brave.app"
The file /Applications/Brave.app does not exist.

open -W "/Applications/Brave Browser.app" opens

**Comment by gregpalaci** [comment]
Sorry I meant this error from before I understand the -R flag now
`$: open -R -a "Brave"
Unable to find application named 'Brave'`

**Comment by AlbertShown** [comment]
Great! Then we should fix this in the code.
Would you like please change [this line](https://github.com/alifcommunity/webui/blob/c89d92fc80b47ab2056598d9cee1f7fffd214355/src/webui.c#L2179) online (_no need for git clone & push_)?

**Comment by AlbertShown** [comment]
Please, let's continue at https://github.com/alifcommunity/webui/issues/75.
