### ISSUE TITLE
what is the exact license?

### ISSUE THREAD

**Issue by retsyo** [alifcommunity/webui#61]
https://github.com/alifcommunity/webui/blob/main/LICENSE says it is LGPL, so if offical DLL is used, the application can be closed-source even for commercial case.

however, https://github.com/alifcommunity/webui/blob/main/README.md says `GNU General Public License v3.0` is applied.
At the same time,  https://github.com/alifcommunity/webui/blob/main/include/mongoose.h uses GPL for Non-Commercial Project, but needs money for Commercial Product.

So what is the exact license for webui? If it is LGPL, maybe it is more friendly for amateur

**Comment by AlbertShown** [comment]
> https://github.com/alifcommunity/webui/blob/main/LICENSE says it is LGPL, so if offical DLL is used, the application can be closed-source even for commercial case.

Yes, that's correct.

> however, https://github.com/alifcommunity/webui/blob/main/README.md says GNU General Public License v3.0 is applied

It's a typo. As we recently switched from `GPL` to `LGPL`.

> At the same time, https://github.com/alifcommunity/webui/blob/main/include/mongoose.h uses GPL for Non-Commercial Project, but needs money for Commercial Product.

We should have been aware of that. Mongoose use `GPLv2`.

> So what is the exact license for webui?

Any suggestion?

**Comment by AlbertShown** [comment]
https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#IfLibraryIsGPL

> If a library is released under the GPL (not the LGPL), does that mean that any program which uses it has to be under the GPL?
> 
> Yes, because the program actually links to the library. As such, the terms of the GPL apply to the entire combination. The software modules that link with the library may be under various GPL compatible licenses, but the work as a whole must be licensed under the GPL.

That means we can use any GPL license we want.

**Comment by AlbertShown** [comment]
Let's go back to `GPLv3`.

**Comment by retsyo** [comment]
I see your post https://github.com/cesanta/mongoose/issues/2133

let's wait for the official answer

**Comment by AlbertShown** [comment]
So, their final answer is we have no other choice. By the GPL v2 requirement, we should follow the same license, which is GPLv2.0.

**Comment by AlbertShown** [comment]
Also, I asked ChatGPT!

**Can I use the MIT license for my open-source project that uses a GPLv2 Third-party library?**

No, you cannot use the MIT license for your open source project if it uses a GPLv2 third-party library. This is because the GPLv2 license is a copyleft license, which means that any derivative works must also be licensed under the same terms as the original work. This would include any code that links or is combined with the GPLv2 library.
