### ISSUE TITLE
watch for URL change

### ISSUE THREAD

**Issue by konsumer** [alifcommunity/webui#67]
Often a login popup-webview needs to show a window, and wait for the URL to change to do things. [Here](https://github.com/notnullgames/goglogin/tree/main) is an example of a login for Gog, written in rust.

Is there a way to do this with webui?

**Comment by hassandraga** [comment]
WebUI is just a library to use web browsers as GUI. The content and behavior of the window are totally under the control of your backend language (Python/Rust) and JavaScript to control the UI. So, yes, you can do it in WebUI.

Can you please tell me more details?

An Example:

```rust
let my_window = Webui::NewWindow();
Webui::Show(my_window, "Your HTML");

let mut js = Webui::JavaScript {
     timeout: 10,
     script: "Something in JavaScript to check the Link or whatever...".to_string(),
     data: "".to_string(),
     error: false,
};

// Loop...
     Webui::RunJavaScript(e.Window, &mut js);
     if js.data == "whatever..."
             // Do something...

Webui::Wait();
```

**Comment by AlbertShown** [comment]
I use Gog. So I tried your Rust and Python examples, but both failed.

**Rust**
```
error[E0425]: cannot find value webview in this scope
  --> src\main.rs:39:3
   |
39 |   webview.open_devtools();
   |   ^^^^^^^ help: a local variable with a similar name exists: _webview

For more information about this error, try rustc --explain E0425.
error: could not compile goglogin due to previous error
```

So, I added `web-view = { version = "0.7", features = ["edge"] }` into `Cargo.toml`

```
error: failed to select a version for `webkit2gtk-sys`.
    ... required by package `webview-sys v0.6.0`
    ... which satisfies dependency `webview-sys = "^0.6"` of package `web-view v0.7.0`
    ... which satisfies dependency `web-view = "^0.7"` of package `goglogin v0.1.0 (C:\Users\xxx\goglogin-main\goglogin-main)`
versions that meet the requirements `^0.12.0` are: 0.12.0
```

**Python**

```
Traceback (most recent call last):
  File "C:\Users\xxx\goglogin-main\goglogin-main\example.py", line 37, in <module>
    tokens = login()
  File "C:\Users\xxx\goglogin-main\goglogin-main\example.py", line 21, in login
    code = subprocess.run(RUNTIME, stdout=subprocess.PIPE).stdout.decode('utf-8').strip()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by konsumer** [comment]
> I see what you mean. For now, there is no built-in feature to catch the navigation events. A workaround is by using navigation.addEventListener("navigate",(event) =>{...} to catch the URL, then send it to your Nim function using webui_fn().

This seems totally fine to me. I think if i just ran a loop to inject that fairly often, if it's not injected, it would basically work the same and be pretty decent. I bet a lot of "host event callback" kind of things could be solved like this, and it doesn;t seem too terrible to me. I think I was just not thinking about the problem, right. Thanks!

> I use Gog. So I tried your Rust and Python examples, but both failed.

Hmm, I will double-check on it. It used to work. The python example is basically just "load this little program to get a token", so if the program doesn't work, the python won't either.

I think the rust issue is with wry/tao dep, or some change I made. I wasn't super-psyched about tao/wry the first place (kinda heavy, sort of funny API, seems like "too much" support-stuff for a simple webview.)

[these builds](https://github.com/notnullgames/goglogin/releases/tag/0.0.0) do work, and came from whatever was setup on Sep 19, 2022.

You can recreate with this:

```
git clone https://github.com/notnullgames/goglogin.git
cd goglogin
git checkout 0.0.0
cargo run
```

**Comment by konsumer** [comment]
This all sort of highlights some nice reasons to do this on webui, other than just "I want to try it with nim". I had other problems getting that library to work on linux, too.

**Comment by konsumer** [comment]
I made some bindings for soloud, pntr, and physfs (see [here](https://github.com/notnullgames/null0/blob/main/src/null0)) that use nim to do the compiling. Similar idea might make it work better:

```nim
{.passC: "-Ivendor/".}

{.emit: """
#define PNTR_IMPLEMENTATION
#define PNTR_PIXELFORMAT_ARGB
#define PNTR_ENABLE_DEFAULT_FONT
#define PNTR_ENABLE_TTF
#define PNTR_ENABLE_FILTER_SMOOTH

/*
PNTR_LOAD_FILE macro should match, for easier physfs
unsigned char* pntr_load_file(const char *fileName, unsigned int *bytesRead);
*/

#include "pntr/pntr.h"
""".}
```

or

```nim
{.passC: "-Ivendor/soloud/src/ -Ivendor/soloud/include/ -DWITH_NULL -DWITH_MINIAUDIO -DWITH_NOSOUND".}
{.compile: "vendor/soloud/src/audiosource/openmpt/soloud_openmpt.cpp".}
```

Basically, I setup the compiler flags in `passC` or `passL` and `emit` and `compile` to inline the C.

**Comment by hassandraga** [comment]
Now, you can listen for URL changes (_Pages including webui.js_), also other general events.

```c
void events(webui_event_t* e) {
    if(e->type == WEBUI_EVENT_NAVIGATION)
        printf("Starting navigation to: %s \n", (char *)e->data);
}

webui_bind(my_window, "", events);
```

If your page opens in an external popup window, you can use JavaScript in your main window to retrieve the URL and then send it back to your function using WebUI `webui_fn('MyNav', url);`.

Thanks again for the URL idea, which leads to adding the events listener to WebUI.
