### ISSUE TITLE
Browsers need to remember the window size and position

### ISSUE THREAD

**Issue by hassandraga** [alifcommunity/webui#68]
Recently Chromium-based browsers do not remember the window size and position anymore. If anyone knows how to tweak this command, please let me know.

**Command:** `"C:\Program Files\Google\Chrome\Application\chrome.exe" --user-data-dir="C:\TestProfile" --no-first-run --disable-gpu --disable-software-rasterizer --no-proxy-server --safe-mode --disable-extensions --disable-background-mode --disable-plugins --disable-plugins-discovery --disable-translate --bwsi --disable-sync --incognito --app=https://google.com`

1. Run the command
2. Change the window size and position
3. Close the window
4. Run the command again

If you are using the latest browser version, probably when you run the command again, the browser won't remember the window size and position.

We can fix this by removing `--incognito`, but many Chromium-based browsers show an account sync notification or a kind of "Welcome" message. Adding `--disable-sync` and `--no-first-run` does not help. The only solution I found is `--incognito`, but the cost is no window size and position restoration.

**Comment by mohamedke** [comment]
We can create an event in JS. When changing the position or size. It does save the value of size and position in a file. Next start of the program, use these values

**Comment by AlbertShown** [comment]
Thank you @mohamedke for the idea. For now, we solved this by simply removing `--incognito`. If we got issues in the future we will then back and use your suggestion.
