### ISSUE TITLE
html استخدام الملفات والسائط داخل (ل.و.ت)

### ISSUE THREAD

**Issue by ms2052001** [alifcommunity/webui#7]
<div dir=rtl>

## وصف المشكلة 

عن استخدام ال css, js مباشرة داخل لغة الوسوم التشعبية (ل.و.ت html)، لا توجد مشكلة وكل يشكل يعمل كما هو متوقع، وكذلك إذا استخدمت رابط لملف موجود على شبكة توصيل محتوى (ش.ت.م CDN).

أما إذا أردنا أن نستخدم ملفات موجودة بجوار الملف التنفيذي الذي تم بناؤه، ولا يجد التطبيق هذا الملف، لأنه لم يتم استضافته على نفس النطاق المحلي localhost.

### تطبيق ال webui.

التطبيق لا يعمل السبب بعد هذا الصورة.

![image](https://user-images.githubusercontent.com/42011920/111881278-68319600-89b8-11eb-9635-c5a32cc01578.png)

التطبيق لا يعمل بسبب مشاكل في الأمان.

![full-paths-security-error](https://user-images.githubusercontent.com/42011920/111881297-797aa280-89b8-11eb-96e2-3362715e2336.png)

### المتصفح

التطبيق أيضا لا يعمل بالمتصفح.

### تطبيق ال webui

كما هو الحال المسارات الكاملة، المسارات النسبية لا تعمل في تطبيق ال webui، مع العلم أن الملفات بجوار الملف التنفيذي الذي تم بناؤه والذي يشغل من الطرفية.

## المتصفح

يعمل بالمتصفح.

![relative-paths-succeed-in-the-browser](https://user-images.githubusercontent.com/42011920/111881304-839ca100-89b8-11eb-8272-5d206884da10.png)

**Comment by ms2052001** [comment]
<div dir=rtl>

أقترح أن يتم إضافة دالة جديدة `showFile` والتي يعطى لها مسار ملف html، وتبقى دالة `show` يعطى لها نص ال html مباشرة.

**Comment by ms2052001** [comment]
<div dir=rtl>

لكن ماذا لو أن لدينا شيئا كهذا:

<div dir=ltr>

```
webui-example
├── my-webui-app.cpp
├── vendors
│   └── another-script.js
└── www
    ├── index.html
    ├── script.js
    └── style.css
```

</div>

- كيف نقوم باستضافة الملفات الموجود في مسار خارج المسار الذي يتواجد به الملف `index.html`؟
-  هل نجبر مستخدمي المكتبة على وضع كل الملفات في مسارات ضمن المسار الذي يوجد به ملف ال html؟
- هل سيتم استضافة "**كل**" الملفات في المسارات التي تندرج تحت المسار الذي يوجد به ملف ال html؟

**Comment by mohamedke** [comment]
أقترح أن نقوم بإضافة أداة تقوم اولا بقراءة الملف الصدري وتحدد الملفات التي يجب أن تستضاف في الخادم المحلي، وبعدها تبدأ عملية الترجمة

**Comment by ms2052001** [comment]
> أقترح أن نقوم بإضافة أداة تقوم اولا بقراءة الملف المصدري وتحدد الملفات التي يجب أن تستضاف في الخادم المحلي، وبعدها تبدأ عملية الترجمة

فكرة رائعة، نريد مكتبة تحلل (parse) ال html وثم بعد يمكننا أن نبحث في ال AST عن أنماط وعقد (node) معينة. سيكون ذلك عن كل مرة يتم استعراض html فيها وليس في عملية البناء.

**Comment by mohamedke** [comment]
> > أقترح أن نقوم بإضافة أداة تقوم اولا بقراءة الملف المصدري وتحدد الملفات التي يجب أن تستضاف في الخادم المحلي، وبعدها تبدأ عملية الترجمة
> 
> فكرة رائعة، نريد مكتبة تحلل (parse) ال html وثم بعد يمكننا أن نبحث في ال AST عن أنماط وعقد (node) معينة. سيكون ذلك عن كل مرة يتم استعراض html فيها وليس في عملية البناء.

صحيح، فكرة جيدة، اظن أني مخطئ، ليس قبل الترجمة، إنما في بداية فتح البرنامج.

**Comment by hassandraga** [comment]
سأحاول إضافة خاصية خدمة ديناميكية لمجلد ما في زمن التنفيذ

**Comment by hassandraga** [comment]
ثم إضافة الخدمة الديناميكية في النسخة 1.0.10

**Comment by hassandraga** [comment]
Example: https://github.com/alifcommunity/webui/blob/main/examples/serve_folder.cpp

**Comment by hassandraga** [comment]
ثم التطوير في ويندوز، أتمنى أن يجربها شخص ما على لينكس

**Comment by me00001** [comment]
> ثم التطوير في ويندوز، أتمنى أن يجربها شخص ما على لينكس
<div dir=rtl>
 كل الأمثلة تظهر الخطأ التالي 
نسخة 10.0.1
</div>


![لقطة شاشة من 2021-04-08 07-22-49](https://user-images.githubusercontent.com/37930867/114076889-dc70a280-98af-11eb-9c2f-60ccfc595c64.png)

**Comment by ms2052001** [comment]
<div dir=rtl>

نظام التشغيل:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
```

الكل يعمل عندي ماعدا custom_browser، حيث تظهر الرسالة التالية دائما.

```
Good! All WebUI windows are closed now.
```

**Comment by ms2052001** [comment]
<div dir=rtl>

توجد مشكلة جديدة، كل الملفات التي تُخْدَم يتم إضافة ذلك الجزء الخاص بمعالجة الاتصال بين المتصفح والخادوم عن طريق الـ WebSocket، الكود التالي يضاف في آخر كل الملفات ولو كانت css أو js.

<div dir=ltr>

```


 <script type = "text/javascript"> 
 const _webui_websocket_port = 8080; 
  const _webui_webserver_port = 8082; 
  const _webui_minimum_data = 1; 
 

		// - - - - - - - - - - -
		// WebUI WebSocket
		// - - - - - - - - - - -

		// external const _webui_websocket_port;
		// external const _webui_webserver_port;
		// external const _webui_minimum_data;

		// Log & keep window open
		const _webui_log = true;

		var _webui_ws;
		var _webui_ws_status = false;
		var _webui_action8 = new Uint8Array(1);
		var _webui_action_val;

		function _webui_close(vbyte, v){

			_webui_ws_status = false;
			_webui_action8[0] = vbyte;
			_webui_action_val = v;
			_webui_ws.close();
		}

		function _webui_start(){
		
			if ('WebSocket' in window){
			
				_webui_ws = new WebSocket('ws://127.0.0.1:' + _webui_websocket_port);
				_webui_ws.binaryType = 'blob';
			
				_webui_ws.onopen = function(){

					_webui_ws.binaryType = 'blob';
					_webui_ws_status = true;					

					if(_webui_log)
						console.log('WebUI -> Connected');
				};

				_webui_ws.onerror = function(){

					if(_webui_log)
						console.log('WebUI -> Connection error');

					_webui_close(0xFF, '');
				};
			
				_webui_ws.onclose = function(){

					_webui_ws_status = false;

					if(_webui_action8[0] == 0xFC){

						if(_webui_log)
							console.log('WebUI -> Switch URL');

						// Switch URL
						window.location.replace(_webui_action_val);
					}
					else {

						// App has exit.
						// WS Error.
						// Window close.

						if(_webui_log)
							console.log('WebUI -> Connection lost');

						if(!_webui_log)
							window.close();
					}
				};

				_webui_ws.onmessage = function (evt){

					var reader;
					var buffer8;

					reader = new FileReader();
					reader.readAsArrayBuffer(evt.data);
					reader.addEventListener("loadend", function(e){

						buffer8 = new Uint8Array(e.target.result);

						if(buffer8.length < _webui_minimum_data)
							return;
						
						if(buffer8[0] !== 0xFF){

							if(_webui_log)
								console.log('WebUI -> Invalid flag -> ' + buffer8[0] + buffer8[1] + buffer8[2]);

							return;
						}

						if(_webui_log)
							console.log('WebUI -> Flag -> ' + buffer8[0] + buffer8[1] + buffer8[2]);

						var len = buffer8.length - 3;

						data8 = new Uint8Array(len);
						for(i = 0; i < len; i++)
							data8[i] = buffer8[i+3];
						
						var data8utf8 = new TextDecoder("utf-8").decode(data8);

						if(buffer8[1] === 0xFC){

							_webui_close(0xFC, data8utf8);
						}
						else if(buffer8[1] === 0xFB){

							_webui_close(0xFB, '');
						}
						else if(buffer8[1] === 0xFE){

							if(_webui_log)
								console.log('WebUI -> JS -> Run -> ' + data8utf8);

							var fun = new Function (data8utf8);
							var FunReturn;
							FunReturn = String(fun());

							if (FunReturn === undefined)
								return;

							if(_webui_log)
								console.log('WebUI -> JS -> Return -> ' + FunReturn);

							var FunReturn8 = new TextEncoder("utf-8").encode(FunReturn);
							var Return8 = new Uint8Array(3 + FunReturn8.length);
							Return8[0] = 0xFF;
							Return8[1] = 0xFE;
							Return8[2] = buffer8[2];

							var p = -1;
							for(i = 3; i < FunReturn8.length + 3; i++)
								Return8[i] = FunReturn8[++p];
							
							if(Return8[0] !== 0xFF){

								if(_webui_log)
									console.log('WebUI -> JS -> Invalid respons -> ' + buffer8[0] + buffer8[1] + buffer8[2]);
								return;
							}

							if(_webui_ws_status)
								_webui_ws.send(Return8.buffer);							

							if(_webui_log){

								var buf = '[ ';
								for(i = 0; i < Return8.length; i++)
									buf = buf + '0x' + Return8[i] + ' ';
								buf = buf + ']';
								console.log('WebUI -> JS -> Send respons -> ' + buf);
							}
						}
					});
				};
			}
			else {
				
				alert('Sorry. WebSocket not supported by your Browser.');

				if(!_webui_log)
					window.close();
			}
		}

		// - - - - - - - - - - -
		// Event
		// - - - - - - - - - - -

		function SendEvent(name){

			if(name != ''){

				var Name8 = new TextEncoder("utf-8").encode(name);
				var Event8 = new Uint8Array(3 + Name8.length);
				Event8[0] = 0xFF;
				Event8[1] = 0xFD;
				Event8[2] = 0x0;

				var p = -1;
				for(i = 3; i < Name8.length + 3; i++)
					Event8[i] = Name8[++p];
				
				if(_webui_ws_status)
					_webui_ws.send(Event8.buffer);				

				if(_webui_log){

					var buf = '[ ';
					for(i = 0; i < Event8.length; i++)
						buf = buf + '0x' + Event8[i] + ' ';
					buf = buf + ']';
					console.log('WebUI -> Event -> Send -> ' + buf);
				}
			}
		}

		window.addEventListener("load",function(){

			var elems = document.getElementsByTagName("form");
			for (i = 0; i < elems.length; i++){

				_webui_ws_status = false;
				alert('Incompatible HTML.\n\nYour HTML contain <form> elements, wish is not compatible with WebUI. Please remove all those elements.');

				_webui_close(0xFF, '');
			}
		
			elems = document.getElementsByTagName("button");
			for (i = 0; i < elems.length; i++){

				if(elems[i].id == '')
					continue;

				if(_webui_log)
					console.log('WebUI -> Listen -> Button -> ' + elems[i].id);
				
				elems[i].addEventListener("click", function(){ SendEvent(this.id) });
			}
			
			elems = document.getElementsByTagName("div");
			for (i = 0; i < elems.length; i++){

				if(elems[i].id == '')
					continue;

				if(_webui_log)
					console.log('WebUI -> Listen -> Div -> ' + elems[i].id);
				
				elems[i].addEventListener("click", function(){ SendEvent(this.id) });
			}
		});

		window.onbeforeunload = function (){

			_webui_close(0xFF, '');
		};		

		_webui_start();

		setTimeout(function(){

			if(!_webui_ws_status){

				//document.body.style.filter = "brightness(1%)";
				document.body.style.filter = "contrast(1%)";
				alert('WebUI failed to find the background application.');

				if(!_webui_log)
					window.close();
			}
		}, 1000);

		// Reload
		document.addEventListener('keydown', function (e){
			if (e.keyCode === 116) {
				e.preventDefault();
				e.returnValue = false;
				e.keyCode = 0;
				return false;
			}		
		});
		// Unload
		window.addEventListener('beforeunload', function (e) {
		  e.preventDefault();
		  e.returnValue = '';
		});
		// Right click
		document.addEventListener('contextmenu', function (e) {
		  //e.preventDefault();
		  //e.returnValue = '';
		});

	 
 </script>
```

**Comment by hassandraga** [comment]
شكرا لكم على التبليغات، كانت قيمة، ثم والحمد لله تصحيحها كلها
نسخة 1.0.11

**Comment by ms2052001** [comment]
<div dir=rtl>

الحمد لله، كل شيء على ما يرام، لكن لما شغلت المثال `serve_folder` من مسار آخر غير الذي يحتويه لم تتمكن WebUI من معرفة مكان الملفات التي يجب خدمتها، إذ أنه يبحث في `pwd`:

<div dir=ltr>

```bash
> pwd
/home/ms/myp/alif/webui/build

> ./examples/serve_folder
```

![image](https://user-images.githubusercontent.com/42011920/114266400-7b071b80-99f6-11eb-8fef-3db26dd05195.png)

**Comment by hassandraga** [comment]
جرب 
my_window.serve_folder("/home/username/.....");

**Comment by hassandraga** [comment]
هذا هو الجزء اللذي يصمم المصار الحالي

https://github.com/alifcommunity/webui/blob/ea3652dd6140e3aa88cc5c0cc521e0cebd23ada2/src/webui.cpp#L697

**Comment by ms2052001** [comment]
> جرب
> my_window.serve_folder("/home/username/.....");

كما توقعنا، اشتغلت.

**Comment by ms2052001** [comment]
<div dir=rtl>

إذن مستخدم مكتبة WebUI هو المطالب بأن يضع المسار الكامل للمصادر؟

**Comment by hassandraga** [comment]
> إذن مستخدم مكتبة WebUI هو المطالب بأن يضع المسار الكامل للمصادر؟

نعم، إذا لم تنجح المكتبة ويب يو أي (بالستخدام مكتبة بوست) في إيجاد المسار
فالمبرمج هو المطلوب بتحديث المسار
