### ISSUE TITLE
Adding Different Browser to macOS?

### ISSUE THREAD

**Issue by gregpalaci** [alifcommunity/webui#75]
https://github.com/alifcommunity/webui/blob/c89d92fc80b47ab2056598d9cee1f7fffd214355/src/webui.c#L2174

I tried adding and rebuilding webUI with Clang this line, along with the 
`webui_open(my_window, url, webui.browser.brave);` in the .ts example. doesn't seem to do anything

building off of issue https://github.com/alifcommunity/webui/issues/59

` #elif __APPLE__

            // Brave on macOS

            if(_webui_cmd_sync("open -R -a \"Brave Browser\"", false) == 0) {

                sprintf(win->core.browser_path, "/Applications/Brave\\ Browser.app/Contents/MacOS/Brave\\ Browser");
                return true;
            }
            else
                return false;`

**Comment by AlbertShown** [comment]
Would you like please change [this line](https://github.com/alifcommunity/webui/blob/c89d92fc80b47ab2056598d9cee1f7fffd214355/src/webui.c#L2179) online (_no need for git clone & push_)?
I guess, it should be `sprintf(win->core.browser_path, "open -W \"/Applications/Brave Browser.app\" --args");`

**Comment by AlbertShown** [comment]
About the TypeScript, this [is an example](https://github.com/alifcommunity/webui/blob/main/examples/TypeScript/Deno/deno_server/deno_server.ts).

```js
// Create new window
const my_window = webui.new_window();

// Create a new server using WebUI (Or any other servers you want, Deno, Nodejs...)
const root_path = "";
const url = webui.new_server(root_path);

// Show the window
if(!webui.open(my_window, url, webui.browser.chrome))
    webui.open(my_window, url, webui.browser.any);

// Wait until all windows get closed
await webui.wait();
```

While writing this example, I discovered we forgot to implement `webui.new_server()` in TypeScript! So, Thank you for pointing this out. I will add it today. It's simple to do.

**Comment by gregpalaci** [comment]
https://github.com/alifcommunity/webui/issues/75#issuecomment-1497934903

No luck, I also tried with `sprintf(win->core.browser_path, "open -W \"/Applications/Brave\\ Browser.app/Contents/MacOS/Brave\\ Browser\" --args");`

**Comment by gregpalaci** [comment]
Just tested this from terminal and it opens a new Brave window
`open -W /Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser`

**Comment by AlbertShown** [comment]
Strange. This is how Chrome works:
`sprintf(win->core.browser_path, "open -W \"/Applications/Google Chrome.app\" --args");`
So, Brave should be:
`sprintf(win->core.browser_path, "open -W \"/Applications/Brave Browser.app\" --args");`

Can you please share the logs?

**Comment by gregpalaci** [comment]
It seems to be hardcoded in the C because when I change the order of these lines it doesnt matter what I call in the typescript UI layer 

below will now use firefox (successfully on mac) even if chrome is listed as in the example. Think the logic isnt working? Not a C expert though. Hope it helps.

https://github.com/alifcommunity/webui/blob/c89d92fc80b47ab2056598d9cee1f7fffd214355/src/webui.c#L2974
`  #elif __APPLE__
            // macOS
             if(!_webui_browser_start_firefox(win, address))`

**Comment by gregpalaci** [comment]
open -W  /Applications/Brave\ Browser.app does work apologies from the command line but see above comment the browsers do seem hardcoded or some sort of if statement default of chrome

**Comment by hassandraga** [comment]
The last commit support all listed web browser in macOS.
