### ISSUE TITLE
WebUI v2.2.0 Proposition

### ISSUE THREAD

**Issue by AlbertShown** [alifcommunity/webui#76]
**WebUI v2.2.0 Proposition**

Some issues are hard to fix, like _Firefox Closing Process Detection_, or some users being confused about how to use `show()` and `open()`. Trying to fix those issues can create other issues.

Other issues exist because we are trying to make WebUI cover many different scenarios. Like we are trying to support `WebUI Server Only`, `WebUI Server + Window`, `Window Only`, etc... I guess **it's better** if we focus on the main reason why WebUI gets created in the first place, which is open a window and connect it to the backend, which is `WebUI Server + Window` scenario.

**I suggest doing this to focus on one scenario:**

1. Remove `webui_open()`
2. Remove `webui_new_server()`
3. Remove process detection code as it does not work with Firefox (_probably other browsers in the future_)
4. Remove `struct` inside `struct` to make wrappers code simpler
5. Make sure all core functions (_Wrappers does not need it_) start with `_webui_xxx`
6. Remove the custom browser code (_Probably no user will need it_)

**Comment by hassandraga** [comment]
Done.
