### ISSUE TITLE
WebUI can not found Google Chrome at Arch Linux (and based distros)

### ISSUE THREAD

**Issue by malisipi** [alifcommunity/webui#77]
Google chrome binary was named as `google-chrome-stable` at Arch Linux and based distros. WebUI should look up the chrome binary before thinking it's not installed.

*Quick Fix until updated Webui library*
* Link the `/bin/google-chrome-stable` to `/bin/google-chrome`

**Comment by hassandraga** [comment]
Sounds good, I'll add it. Thank you for pointing that out.
