### ISSUE TITLE
time to leave Boost ?

### ISSUE THREAD

**Issue by hassandraga** [alifcommunity/webui#8]
Is there any other open source lib that support WebSocket and HTTP server, multi threading, free, and using only standard C++ ?

**Comment by xlmnxp** [comment]
> Is there any other open source lib that support WebSocket and HTTP server, multi threading, free, and using only standard C++ ?

You can build your, using bulit in unix sockets

**Comment by hassandraga** [comment]
In my opinion, the secured handshake stage, and asynchronous features will take a  lot of time, I suggest for now keeping Boost.
