### ISSUE TITLE
The deno example instructions are too vague

### ISSUE THREAD

**Issue by davidbludlow** [alifcommunity/webui#80]
I tried to follow the instructions at `examples/TypeScript/Deno/deno_server/README.md` and `examples/TypeScript/Deno/hello_world/hello_world.ts` but Step 2 was so vague that I didn't know how to do it.

Yes, I knew how to click on the link and download the .zip file, but which parts of the zip file do I extract to what folders? As a TypeScript developer, I am unfamiliar with the differences between GCC, MSVC, and TCC.

I tried several things, but I wasn't able to get it to work.

**Comment by hassandraga** [comment]
I'm sorry about that. A better documentation will come  after publishing the new version `v2.2.0` very soon (with pre-built binaries ready to use).

For now, you need to build WebUI from source using GCC, MSVC, Clang or TCC. After that you need to copy the dll file into `examples/TypeScript/Deno/module`.

The `deno_server` example will be removed soon. Please use `deno hello world`.

**Comment by davidbludlow** [comment]
Well, that will be nice when that documentation is done. I couldn't quickly figure out how to build it, but I did download webui-2-x64.dll and put it in `examples/TypeScript/Deno/module` and got the following error when I tried to run with deno:

```
PS C:\Users\HP\Desktop\webui\examples\TypeScript\Deno\hello_world> deno run --allow-all --unstable hello_world.ts
error: Uncaught Error: Failed to register symbol webui_clean_mem: Could not obtain symbol from the library: The specified procedure could not be found. (os error 127)
  webui_lib = Deno.dlopen(
                   ^
    at new DynamicLibrary (ext:deno_ffi/00_ffi.js:440:46)
    at Object.dlopen (ext:deno_ffi/00_ffi.js:570:10)
    at load_lib (file:///C:/Users/HP/Desktop/webui/examples/TypeScript/Deno/module/webui.ts:114:20)
    at Module.new_window (file:///C:/Users/HP/Desktop/webui/examples/TypeScript/Deno/module/webui.ts:179:3)
    at file:///C:/Users/HP/Desktop/webui/examples/TypeScript/Deno/hello_world/hello_world.ts:83:25
```
I can wait for the documentation, though.

**Comment by hassandraga** [comment]
That's because the pre-built binaries are outdated. To get the latest DLL version `2.1.1` you need to build WebUI from source. Or, You can wait for `2.2.0`, it will be published very soon.

In other hand, I can share with you here the WebUI Deno v2.2.0 example ready to use, and you test it before we publish it.

**Comment by davidbludlow** [comment]
Cool

**Comment by davidbludlow** [comment]
Yes! That works! Thanks!
