### ISSUE TITLE
Linking errors MSVC2022

### ISSUE THREAD

**Issue by cassw2** [alifcommunity/webui#83]
Getting a lot of errors while linking a simple webui example related with "ws2def.h" and "winsock2.h"

E0040	expected an identifier	example	C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ws2def.h	442	ws2def.h
........
E0338	more than one instance of overloaded function "__WSAFDIsSet" has 'C' linkage	example	C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\WinSock2.h	141	
........

So I commented both files on webui.h  and now I get a single error:
Error	LNK1104	cannot open file 'C:\webui_2.0.6\Windows\MSVC.obj'

Any clue of what's the cause of this?

**Comment by hassandraga** [comment]
This is a linking issue related to the VS project configuration that you are using. Could you give me more info about how you added WebUI lib to your project?

Meanwhile, You can try the new [WebUI v2.2.0](https://github.com/alifcommunity/webui/tree/WebUI_v2.2.0).

In general, this is how you can add WebUI (static) to your VS project:

1. Create a new VS project without GUI (console)
2. Make sure you can build and run
3. Add `webui-2-static-x64.lib` as static dependencies
4. Make sure you also have `Ws2_32.lib`, `user32.lib` and `Advapi32.lib`
5. Add `webui.h`
6. Change linking from `console` to `windows`

So that you know, all those steps should be done in your project proprieties.

**Comment by cassw2** [comment]
Thanks for the answer.

I was putting the previous example into an existing project (with many libs and includes from QT), maybe it was the source of those errors. So I did all your steps and got a new example running from a new empty msvc project and also using new version WebUI_v2.2.0.

I noticed the example on docs is no longer updated because on new version the webui_window_t is now gone, but I did it this way:

`extern "C" {
    #include "webui.h"
}


#include <iostream>

int main()
{
    void* my_window = webui_new_window();
    webui_show(my_window, "<html>Hello</html>");
    webui_wait();
    return 0;

}

#if defined(_MSC_VER)
int APIENTRY WinMain(HINSTANCE hInst, HINSTANCE hInstPrev, PSTR cmdline, int cmdshow) {
    main();
}
#endif
`

**Comment by AlbertShown** [comment]
Yes, `webui_window_t` is removed, and many other things get optimized to make wrappers more efficient (_TS, Go, Python, Nim, Zig, Rust..._).

You can find _v2.2.0_ examples that you can use in your new project here:
https://github.com/alifcommunity/webui/tree/WebUI_v2.2.0/examples/C

**Comment by cassw2** [comment]
I started doing some testing, passing some index.html files to webui_show, some simple site templates I had. They all start and show up and run okay but after 10 seconds the debug window is automatically shut down (if inside msvc) but app window stays up, and site is unresponsive. 
Something is triggering webui_wait(); but I only let the app start and run doing nothing and it goes down automatically after 10s. What am I missing here?

**Comment by AlbertShown** [comment]
I'm creating a new C++ VS2019 example project that supports WebUI v2.2.0. I will share it, and let's see if it's fixing this issue.

**Comment by cassw2** [comment]
> I'm creating a new C++ VS2019 example project that supports WebUI v2.2.0. I will share it, and let's see if it's fixing this issue.

Curious is that by creating the html content on the app like this:

```
const char* my_html =
        "<html>"
        "  <head>"
        ........
        "</html>";

webui_show(my_window, my_html);

```

It works fine.

But if I save the exact html content on a html file and call it like this:
`webui_show(my_window, "index.html");`

The issue happens, unresponsive, 10seconds and it quits.

**Comment by hassandraga** [comment]
I just added [VS2019](https://github.com/alifcommunity/webui/tree/WebUI_v2.2.0/examples/C%2B%2B/VS2019/serve_a_folder) and [VS2022](https://github.com/alifcommunity/webui/tree/WebUI_v2.2.0/examples/C%2B%2B/VS2022/serve_a_folder) C++ examples. While doing this, I discovered a memory issue when using Visual Studio, and it got fixed, so thank you for the report.

![image](https://user-images.githubusercontent.com/16948659/233817403-079383f9-6859-4f00-930b-96e383b247a5.png)

**Comment by hassandraga** [comment]
The 10 seconds issue can be an environmental issue since it works fine using an embedded HTML. To know exactly what's going on, please follow the steps:

1. Start `x64 Native Tools Command Prompt for VS 2022`
2. cd `webui\build`
3. `windows_build debug`
4. Open `webui\examples\C++\VS2022\serve_a_folder\my_webui_app.sln`
5. Build in `Debug` mode, then run

This will trigger a console window with the full WebUI logs. Please copy the logs and share them here.

_Note: `windows_build debug` will build WebUI in debug mode using MSVC, GCC and TCC, so ignore errors in case you don't have GCC or TCC._

**Comment by cassw2** [comment]
I did the building and run your vs2022 solution, it worked fine. Then i did some digging on the actual html files of the examples and noticed this line here at the end of each html file:

**!-- Connect this window to the background app --
<script src="/webui.js"></script>**



We're supposed to add this line to every html file that our program uses? If so I didn't see it mentioned on the docs.
After I do that I no longer have the 10s exit issue if I leave the program idle, but if I do some clicking interaction on the html file it can randomly exit or not after a while.

**Comment by hassandraga** [comment]
I still need to finish the v2.2.0 documentation, but I'm working on it today.
About the `<script src="/webui.js"></script>` it's already mentioned in the actual [online docs](https://webui.me/docs/#/c_api?id=server), but I should clarify it.

**Comment by hassandraga** [comment]
Can you please share the logs so we can identify why the app exited after some clicks?
I already test it by clicking quickly and multiple times on almost all examples, and it always works fine.

**Comment by cassw2** [comment]
> Can you please share the logs so we can identify why the app exited after some clicks? I already test it by clicking quickly and multiple times on almost all examples, and it always works fine.

The problem is not on the examples, those also work fine here. Issues happen when I start passing some basic html site templates and play around with them using webui.

Now by inserting the "<script src="/webui.js"></script>" at the end of index.html files, I don't have the 10s exit issue but I can get random exits or unresponsive behavior.

**Comment by hassandraga** [comment]
I got it. I mean, reading the WebUI logs can tell us the reason behind those random exits. It can be a WebSocket issue, a JavaScript issue, a bug in the WebUI core functionality or something else. By sharing the logs, I can help you fix your issue 👍

**Comment by cassw2** [comment]
Actually it was kind of simple the source of random exits, when html files have href="#"

`<li><a href="#">Home</a></li>`
when you click on that link it get disconnected and app exit. If I remove the # (change to href="") the app then reloads the page okay, disconnect and connect again, and keeps up (no exit).

**Comment by hassandraga** [comment]
You are right. It's a bug. I'm working on it.
Thank you for the report 👍

**Comment by hassandraga** [comment]
I added this [javascript function](https://github.com/alifcommunity/webui/blob/527d000b45fadf5fa5f81682a9816573abbc3e1b/src/webui.c#L170) to fix this issue.
