### ISSUE TITLE
manually adding browser link

### ISSUE THREAD

**Issue by mohamedke** [alifcommunity/webui#9]
إن أمكن إضافة خاصية اختيار مسار المتصفح يدويا، في حالة كان الشخص يريد اختيار متصفح ما أو لايوجد لديه المتصفحات المدعومة

**Comment by hassandraga** [comment]
Good idea!

**Comment by mohamedke** [comment]
@hassandraga  شكرا لك

**Comment by hassandraga** [comment]
https://github.com/alifcommunity/webui/blob/main/examples/custom_browser.cpp

**Comment by hassandraga** [comment]
جرب هذا المثال
فإن عمل في لينكس  وويندوز
يمكنك بعدها إغلاق

**Comment by me00001** [comment]
> https://github.com/alifcommunity/webui/blob/main/examples/custom_browser.cpp

<div dir=rtl>
ميزة مفيدة :+1:  استبدلت التالي
</div>

https://github.com/alifcommunity/webui/blob/1905918175d79ed956f299800e3389b4bd2205fa/examples/custom_browser.cpp#L51-L53

<div dir=rtl>
بالشفرة التالية
</div>

``` cpp
		.app = "epiphany",
		.arg = "--private-instance ",
		.link = true
```

<div dir=rtl>
يعمل المتصفح 
</div>

![لقطة شاشة من 2021-03-26 17-38-40](https://user-images.githubusercontent.com/37930867/112648461-9ac90c00-8e5a-11eb-9177-788c0e7ccb2b.png)

<div dir=rtl>
ولكن عند اغلاق المتصفح يظهر الخطأ التالي بتكرار لا نهائي
</div>

``` 
[!] Error: {session} -> read: Operation canceled
[!] Error: {session} -> read: Operation canceled
[!] Error: {session} -> read: Operation canceled
[!] Error: {session} -> read^C
```

**Comment by hassandraga** [comment]
شكرا لك

**Comment by mohamedke** [comment]
كروميوم اشتغلت هكذا
webui::custom_browser_t MyBrowser {

		// Firefox on Linux
		// Command: 'firefox -private -url http://127.0.0.1:1234'

		.app = "chromium",
		.arg = "--new-window -app=",
		.link = true
	};
