### ISSUE TITLE
Chromium should be used on Linux

### ISSUE THREAD

**Issue by TeddyDD** [alifcommunity/webui#90]
Some distros ship chromium (FOSS Chrome build) under binary name `chromium`. I don't know much C, but it seems that currently webui searches for chromium only on macOS. Since Chromium/chrome has better app mode, it would be nice to try to use it on Linux as well.

**Comment by hassandraga** [comment]
https://github.com/alifcommunity/webui/blob/6ef37f068ad787605713bf93eae9cab49772b8b9/src/webui.c#L2797

Right now, WebUI searches for Chromium on Linux using `chromium-browser`. Are you saying that Chromium in your Linux distro uses `chromium`? If yes, we can easily add it to the search commands.

Can you please provide your Linux distribution name?

**Comment by TeddyDD** [comment]
Yes.

| distro | binary |
|-|-|
| Ubuntu | chromium-browser |
| Arch | chromium |
| Void | chromium |
| Linux Mint | chromium |
| Fedora | chromium-browser | 
| open suse | both 😉 | 
| alpine | chromium-browser |

**Comment by AlbertShown** [comment]
Thank you, @TeddyDD 👍
Added https://github.com/alifcommunity/webui/pull/92
